### ISSUE TITLE
Change from ggplot to node_baplot

### ISSUE THREAD

**Issue by Hapfelmeier** [Hapfelmeier/coat#7]
I like the idea but see several problems:
1. The labeling and plotting is overlapping a lot, which needs to be solved but may be a minor issue.
2. The ggplot version allowed to set digits = 2 and level = 0.95, which is needed.
3. The plotting of BAtest would also have to be adapted accordingly. And it includes also a display of the test statistics (which we may choose to remove, admittedly).

What do you think about these problems?

**Comment by zeileis** [comment]
As suggested in Issue https://github.com/Hapfelmeier/coat/issues/6 the PR https://github.com/Hapfelmeier/coat/pull/8 now proposes to offer both visualization interfaces for `coat`:

* A `plot()` method that follows the classic `partykit` plotting in `grid` directly via panel functions and panel-generating functions.
* An `autoplot()` method that leverages the `ggparty` approach based on `ggplot2`.

So users can choose the visualization engine they prefer. Regarding the problems you raised:

1. In the proposed `plot()` method you can set the `xscale` via `tp_args` in order to extend the x-axis scale.
2. These can also be set but via `tp_args` (terminal panel arguments), the proposed manual page has an example for this.
3. For `BAtest` we could follow the same approach and provide both a `plot()` and an `autoplot()` method. If the statistics should be part of both, this is surely doable but I would have to check how exactly. But I remember that Heidi had code like that in a paper (pre-`ggparty`).

**Comment by Hapfelmeier** [comment]
All solved.
